### ISSUE TITLE
[BUG/ISSUE] Error parsing rate expressions if the RHS of an equation is longer than ~100 chars

### ISSUE THREAD

**Issue by yantosca** [geoschem/KPP#1]
I am using KPP on the GC_updates branch and have noticed some weird behavior when using the more recent GCC compilers.  For example, if I put kind parameters on numeric constants in my equation file, e.g.
```
ISOP + OH = 0.3MCO3 + 0.3MGLY + 0.3CH2O +
 0.15HPALD3 + 0.25HPALD1 + 0.4HO2 +
 0.6CO + 1.5OH + 0.3HPETHNL + LISOPOH :      GC_ISO2(1.7E-11_dp, 390.0_dp, 9.33E-2_dp, 5.05E15_dp, -12200.0_dp, 1.79E14_dp, -8830.0_dp); {2019/11/06; Bates2019; KHB}
```
KPP will parse this output and write to gckpp_Rates.F90 as:
```
  RCONST(396) = (GC_ISO2(1.7E-11_dp,390.0_dp,9.33E-2_dp,5.05E15_dp,-12200.0_dp,1.79E14_dp,-8830.0390.0_dp,9.33E-2_dp,&
                  &5.05E15_dp,-12200.0_dp,1.79E14_dp,-8830.0_dp)
```
Note that after the number -8830 it seems to be appending the earlier part of the line.  I imagine this might be a string buffer being too small, but I don't know where in the KPP C code to fix this.

KPP source code directory
- [KPP-Code.zip](https://github.com/geoschem/KPP/files/5696956/KPP-Code.zip)

Build directory:
- [KPP.zip](https://github.com/geoschem/KPP/files/5696937/KPP.zip)

If you have any ideas as to how to fix this issue, please let me know.  Thanks!

Cc: @msulprizio @LiamBindle @khbates @WilliamDowns

**Comment by LiamBindle** [comment]
I took a look---sorry I'm not sure I have much to add here. This might be a bit of a hail mary, but there's a PP definition for `MAX_BUFFER` in `src/scanutils.c` and it's 200 characters. Two hundred characters is exactly 

```
= 0.3MCO3 + 0.3MGLY + 0.3CH2O +
 0.15HPALD3 + 0.25HPALD1 + 0.4HO2 +
 0.6CO + 1.5OH + 0.3HPETHNL + LISOPOH :      GC_ISO2(1.7E-11_dp, 390.0_dp, 9.33E-2_dp, 5.05E15_dp, -12200.0_dp, 1.79E14_dp, -8830.0
```
plus a null character at the end. That might just be a coincidence though.

**Comment by yantosca** [comment]
Thanks @LiamBindle.  I tried setting:
```C
#define MAX_BUFFER 1000  (scanutils.c)
#define MAX_K          1000 (gdata.h)
#define MAX_EQNLEN     1000 (gdata.h)
```
but that doesn't seem to solve the issue.  

I think the splitting of rows into continuation characters happens in F90_WriteAssign:
```C
void F90_WriteAssign( char *ls, char *rs )
{
int start;
int linelg;
int i, j;
int ifound, jfound;
char c;
int first;
int crtident;

/* Max no of continuation lines in F90/F95 differs with compilers, but 39
                               should work for every compiler*/
int number_of_lines = 1, MAX_NO_OF_LINES = 36;

/*  Operator Mapping: 0xaa = '*' | 0xab = '+' | 0xac = ',' 
                      0xad = '-' | 0xae ='.' | 0xaf = '/' */		      
/* char op_mult=0xaa, op_plus=0xab, op_minus=0xad, op_dot=0xae, op_div=0xaf; */		      
char op_mult='*', op_plus='+', op_minus='-', op_dot='.', op_div='/';		      
  
  crtident = 2 + ident * 2;
  bprintf("%*s%s = ", crtident, "", ls);
  start = strlen( ls ) + 2;
  linelg = 120 - crtident - start - 1; /* F90 max line length is 132 */

  first = 1;
  while( strlen(rs) > linelg ) {
    ifound = 0; jfound = 0;
    if ( number_of_lines >= MAX_NO_OF_LINES ) {
     /* If a new line needs to be started. 
          Note: the approach below will create erroneous code if the +/- is within a subexpression, e.g. for
          A*(B+C) one cannot start a new continuation line by splitting at the + sign */
     for( j=linelg; j>5; j-- ) /* split row here if +, -, or comma */
       if ( ( rs[j] == op_plus )||( rs[j] == op_minus )||( rs[j]==',' ) ) { 
        jfound = 1; i=j; break;
	}
    }
    if ( ( number_of_lines < MAX_NO_OF_LINES )||( !jfound ) ) {
     for( i=linelg; i>10; i-- ) /* split row here if operator or comma */
       if ( ( rs[i] & 0x80 )||( rs[i]==',' ) ) {
        ifound = 1; break;
	}
     if( i <= 10 ) {
       printf("\n Warning: double-check continuation lines for:\n   %s = %s\n",ls,rs);
       i = linelg;
     }
    } 
    while ( rs[i-1] & 0x80 ) i--; /* put all operators on the next row */
    while ( rs[i] == ',' ) i++;   /* put commas on the current row */
    
    c = rs[i]; 
    rs[i] = 0;
    
    if ( first ) { /* first line in a split row */
      bprintf("%s", rs ); 
      linelg++;
      first = 0;
    } else {/* continuation line in a split row - but not last line*/
      bprintf("&\n     %*s&%s", start, "", rs );		
      if ( jfound ) {
         bprintf("\n%*s%s = %s", crtident, "", ls, ls);
	 number_of_lines = 1;
	 }
    }  
    rs[i] = c;
    rs += i;  /* jump to the first not-yet-written character */
    number_of_lines++;
  }
  
  if ( number_of_lines > MAX_NO_OF_LINES ) {
     printf("\n Warning: %d continuation lines for %s = ...",number_of_lines,ls);
     }

  if ( first ) bprintf("%s\n", rs );  /* non-split row */
          else bprintf("&\n     %*s&%s\n", start, "", rs ); /* last line in a split row */


  FlushBuf();
}
```
also the 
```
 while ( rs[i-1] & 0x80 ) i--; /* put all operators on the next row */
```
seems to hardcode break lines at 80 characters (or at least that's what my rusty C tells me).

For now I can hand-edit (or sed) the code but this'd be nice to fix.

**Comment by drewpendergrass** [comment]
Just jumping on here to say that I had modified some reactions so I could do gradient descent to optimize scaling factors, but had some KPP issues in gcc 9.3.0. For example, I write the reaction:

 ```
IHOO1 = 0.15ISOP1CO2OOH + 0.25ISOP1CO4OOH + 0.4HO2 + 0.6CO + 1.5OH + 0.3HCHO + 0.3MGLY + 0.3HPETHNL + 0.3CH3CO3 : (  (TEMP*5.1242E-5-0.0128)*5.05E15*EXP(-12200./TEMP)*EXP(1.E8/TEMP**3) ) * RATEMULT(20);
```

KPP gives the following warning for one line, and similar warnings for several more lines:

```
Warning: double-check continuation lines for:
   RCONST(20) = (((TEMP*5.1242E-5-0.0128)*5.05E15*EXP(-12200./TEMP)*EXP(1.E8/TEMP**3))*RATEMULT(2(TEMP*5.1242E-5-0.0128)*5.05E15*EXP(-12200./TEMP)*EXP(1.E8/TEMP**3))*RATEMULT(20)*RAEMU(NIT(2.7E-12,350.,1.297,6.,1.2038,9.04E-4))*RATEMULT(21))
```

It seems that in parsing this quite long reaction KPP garbles it with the next line. However, the next reaction does just fine. Here's an excerpt from the produced Rates file.

```
RCONST(20) = (((TEMP*5.1242E-5-0.0128)*5.05E15*EXP(-12200./TEMP)*EXP(1.E8/TEMP**3))*RATEMULT(2(TEMP*5.1242E-5-0.0128)*&
                 &5.05E15*EXP(-12200./TEMP)*EXP(1.E8/TEMP**3))*RATEMULT(20)*RA^AEMU(NIT(2.7E-12,350.,1.297,6.,1.2038,&
                 &9.04E-4))*RATEMULT(21))
  RCONST(21) = ((NIT(2.7E-12,350.,1.297,6.,1.2038,9.04E-4))*RATEMULT(21))
```

This garbling issue is odd and I'm not quite sure what to make of it.

**Comment by yantosca** [comment]
A quick fix for this issue: Compile the KPP code with an older compiler version. I built KPP with the default compiler on our Cannon cluster (i.e. /usr/bin/gcc, which is gcc version 4.8.5) and I now get this output:
```
  RCONST(396) = (GC_ISO2(1.7E-11_dp,390.0_dp,9.33E-2_dp,5.05E15_dp,-12200.0_dp,1.79E14_dp,-8830.0390.0_dp,9.33E-2_dp,&
                  &5.05E15_dp,-12200.0_dp,1.79E14_dp,-8830.0_dp))
```
This now breaks the line properly. 

So it would appear that the newer GNU and Intel C compilers have some kind of different behavior regarding strings or pointers to strings that results in the error listed a few comments above.

**Comment by yantosca** [comment]
Also update, after some research I found:
```
while ( rs[i-1] & 0x80 ) i--; /* put all operators on the next row */
```
that the bitwise and with hex value 0x80 is just testing if the string is one of the "Base ASCII" characters (indices 0-127 in the ASCII table).

As I said before, my C is rusty.

**Comment by yantosca** [comment]
Actually I was mistaken.  It is still doubling the characters
```
-8830.0390.0_dp
```

**Comment by RolfSander** [comment]
Have you tried to increase MAX_K in gdata.h? Maybe

#define MAX_K           200

Also, whenever you increase MAX_K, it seems to be necessary to increase
four arrays in scan.l:

char crtToken[200]; 
char nextToken[200];
char crtFile[200];  
char crt_rate[200];

**Comment by yantosca** [comment]
Will definitely try that @RolfSander.  Thanks for the tip!

**Comment by yantosca** [comment]
This has been done in commit  d52075da819f858e953dc89dfba6957bf1c6baad.  I can close out this issue now.

**Comment by yantosca** [comment]
I have discarded the commit d52075da819f858e953dc89dfba6957bf1c6baad as well as the entire GC_experimental branch.  I have made this fix (currently on the dev branch) in commit a691bbb95799cce0289e70aa1d1c8fbd0e215537.  This is slated to go into KPP version 2.3.3._gc.
