### ISSUE TITLE
Modifying chemistry in v12.5.0 and prior versions

### ISSUE THREAD

**Issue by jingqiumao** [geoschem/KPP#3]
If I want to modify chemistry in the model for the versions prior to v12.5.0 (cmake is not available), is the best way to modify "Tropchem.eqn" or "Standard.eqn", and run build_mechanism.sh in that directory?

**Comment by yantosca** [comment]
Yes, that is correct.  I forget if there is a build_mechanism.sh in the KPP folder for 12.5.0 or if we started it for 12.6.0.  If there isn't one you can just run the KPP executable on the gckpp.kpp file in Tropchem or Standard.

Also make sure you are using KPP 2.2.4_gc with versions prior to 13.0.0.

**Comment by jingqiumao** [comment]
Thanks Bob!
