### ISSUE TITLE
[BUG/ISSUE] Hitting the maximum limit of characters for inline code in gckpp.kpp

### ISSUE THREAD

**Issue by yantosca** [geoschem/KPP#7]
I've been adding several rate-law functions (with comments) to the gckpp.kpp file for my mechanism.  However, it seems like I have come up against the maximum number of characters limit.  Basically I have a gckpp.kpp file (attached here) in which I have added this function in the middle:

```F90
  FUNCTION GCJPLPR_abcabc( a1, b1, c1, a2, b2, c2, fv ) RESULT( k )
      ... etc omitted for clarity ...
   END FUNCTION GCJPLPR_abcabc

  !#########################################################################
  !#####          RATE-LAW FUNCTIONS FOR SULFATE REACTIONS             #####
  !#####                                                               #####
  !#####     Use "=>" to denote fields of derived-type objects;        #####
  !#####     KPP 2.3.2_gc+ will convert them to percent signs.         #####
  !#########################################################################

  FUNCTION AqRate_SALAAL_SO2_O3( H ) RESULT( k )
    !
    ! Computes the rate constant [1/s] for the equation
    ! SO2  + SALAAL + O3  = SO4 - SALAAL 
    !
    TYPE(HetState), INTENT(IN) :: H              ! Hetchem State
    REAL(dp)                   :: k              ! rxn rate [1/s]
    !
    k = 0.0_dp
    !
    ! NOTE: We need to use the concentration of SALAAL prior to its
    ! conversion to equivalents.  This is in H%SALAAL_save.
    IF ( H=>SALAAL_save > 0.1_dp ) THEN
       k = Ars_L1K( H=>wetArea(SSA), H=>xRadi(SSA), 0.11_dp, SR_MW(ind_SO2) 
    
      ! Assume SO2 is limiting, so recompute reaction rate accordingly
      k = kIIR1Ltd( C(ind_SO2), C(ind_O3), k ) / H=>SALAAL_save
    ENDIF
  END FUNCTION AqRate_SALAAL_SO2_O3

  !#########################################################################
  !#####        RATE-LAW FUNCTIONS FOR HETEROGENEOUS REACTIONS         #####
  !#####                                                               #####
  !#####     Use "=>" to denote fields of derived-type objects;        #####
  !#####     KPP 2.3.2_gc+ will convert them to percent signs.         #####
  !#########################################################################

  !=========================================================================
  ! General functions (used by rate-law functions below)
  !=========================================================================

  FUNCTION Ars_L1k( area, radius, gamma, srMw ) RESULT( k )
   ... etc omitted for clarity ...
  END FUNCTION Ars_L1k
```
and the generated gckpp_Rates.F90 file looks like this:
```F90
  END FUNCTION GCJPLPR_abcabc

  !#########################################################################
  !#####          RATE-LAW FUNCTIONS FOR SULFATE REACTIONS             #####
  !#####                                                               #####
  !#####     Use "%" to denote fields of derived-type objects;        #####
  !#####     KPP 2.3.2_gc+ will convert them to percent signs.         #####
  !#########################################################################

  FUNCTION AqRate_SALAAL_SO2_O3( H ) RESULT( k )
    !
    ! Computes the rate constant [1/s] for the equation
    ! SO2  + SALAAL + O3  = SO4 - SALAAL 
    !
    TYPE(HetState), INTENT(IN) :: H              ! Hetchem State
    REAL(dp)                   :: k              ! rxn rate [1/s]
    !
    k = 0.0_dp
    !
    ! NOTE: We need to use the concentration of SALAAL prior to its
    ! conversion to equivalents.  This is in H
! End INLINED Rate Law Functions
```
As you can see, it doesn't finish writing the end of this function. Right now I have set:
```C
#define MAX_INLINE 200000
```
in `scan.h`.  I figured that this was too low so I tried increasing it to a large number like `800000`, but I still get the same output.  If I increase it further to `1000000` I get a seg fault, which means that I probably don't have enough memory on the node of the machine that I am using.

@RolfSander @mslv3: Can you suggest anything else to try?  I could of course shorten the functions in `gckpp.kpp` by removing comments but then we'd lose all documentation.

gckpp.kpp:
  - [gckpp.kpp.txt](https://github.com/geoschem/KPP/files/6632916/gckpp.kpp.txt)

**Comment by yantosca** [comment]
Or if there is a way to keep the comments in gckpp.kpp, but have KPP/flex filter them out when writing to gckpp_Rates.F90, that might be the best solution.  The gckpp_Rates.F90 doesn't have to be human-readable but the gckpp.kpp should be.

**Comment by RolfSander** [comment]
I never had any problems with this. Increasing MAX_INLINE in scan.h has
always worked for me. I currently use a value of 100000, which is
sufficient for me.

An alternative for you may be to put the new functions into a separate file
called my_rate_law_functions.f90, and then include that via F90_RCONST:
```
#INLINE F90_RCONST
  ...
  USE my_rate_law_functions
  ...
#ENDINLINE
```
This could also make it easier to use percent signs for derived-type
objects.

**Comment by yantosca** [comment]
Thanks @RolfSander, I will try that!  Such an obvious solution (I was looking at some kind of C-language modification but that is way more straightforward).

**Comment by yantosca** [comment]
@RolfSander: I tried this but the problem is that the USE statement gets placed below the CONTAINS statement in gckpp_Rates:

```F90
MODULE gckpp_Rates

  USE gckpp_Parameters
  USE gckpp_Global
  IMPLICIT NONE

CONTAINS



! Begin INLINED Rate Law Functions


  ! Use this module which contains rate law definitions
  ! This is necessary as a workaround for KPP not being able to
  ! include very large files ( > 200000 chars) directly.
  !  -- Bob Yantosca (10 Jun 2020)
  USE aerochem_RateLawFuncs
```
However, this should work if I use 
```F90
#include aerochem_RateLawFuncs.H
```
instead.  Trying that next. 

I could also modify this code in gen.c to add a USE statement:
```C
     UseFile( rateFile );
     F90_Inline("MODULE %s_Rates\n", rootFileName );
     if ( useDeclareValues )
       F90_Inline("  USE %s_Precision", rootFileName );
     else
       F90_Inline("  USE %s_Parameters", rootFileName );
     F90_Inline("  USE %s_Global", rootFileName );
//-------------------------------------------------------------------
// Add a module use statement for user-defined rate-law functions
// as a workaround for KPP not being able to inline large files 
// (bmy, 10 Jun 2020)
     F90_Inline("  USE %s_Rate_Law_Functions", rootFileName );
//-------------------------------------------------------------------
     F90_Inline("  IMPLICIT NONE", rootFileName );
     F90_Inline("\nCONTAINS\n\n");
```
but this is more hardwired so I think I'll stick with the include file approach (which doesn't require code modifications).

**Comment by RolfSander** [comment]
Did you use `#INLINE F90_RATES`? I am using `#INLINE F90_RCONST` which
puts the USE command directly into the SUBROUTINE UPDATE_RCONST. For me,
this is fine. However, if you also need your new rate-law functions
somewhere outside of SUBROUTINE UPDATE_RCONST, my suggestion won't work for you.

**Comment by yantosca** [comment]
Thanks @RolfSander. I was indeed able to get the USE statement directly into Update_RCONST with `#INLINE F90_RATES`.  So that's my solution.

The only thing is that I seem to be getting a segfault if I don't have both e.g. 
```F90
#INLINE F90_RCONST
   USE aerochem_RateLawFuncs
#ENDINLINE

#INLINE F90_RATES
  ! Nothing to inline
#ENDINLINE
```
so I am looking into that now.   It could be related to a modification that I've made.

**Comment by yantosca** [comment]
Going to close this issue for now.   I have the rate function inlined into Update_RConst and that is working well.
